name: student-ai-assistant
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - flask=2.3.*
  - requests
  - python-dotenv
  - werkzeug=2.3.*
  - pip:
    - azure-search-documents==11.5.2
    - azure-core
    - azure-identity
    - python-docx  # For processing .docx files
    - pdfplumber   # For processing PDF files
    - markdown     # For processing .md files
    - pymongo      # For MongoDB Atlas integration